
--1 List all the states in which we have customer who have bought cell phones from 2005 till today

SELECT STATE FROM DIM_LOCATION L INNER  JOIN  FACT_TRANSACTIONS F ON L.IDLocation = F.IDLocation
WHERE F.Date >= '2005' AND F.Date <= GETDATE();

--2 WHAT STATE IN US IS BUYING MORE 'SAMSUNG' CELLPHONES

SELECT TOP 1 STATE , SUM(Quantity) [QUANTITY] FROM DIM_LOCATION L INNER JOIN FACT_TRANSACTIONS F 
ON L.IDLocation = F.IDLocation 
INNER JOIN DIM_MODEL M1
ON F.IDModel = M1.IDModel
INNER JOIN DIM_MANUFACTURER M2 
ON M1.IDManufacturer = M2.IDManufacturer
WHERE COUNTRY = 'US' AND Manufacturer_Name = 'SAMSUNG'
GROUP BY STATE
ORDER BY SUM(QUANTITY) DESC

--3. Show the number of transaction for each model per zipcode per state.

SELECT IDModel,COUNT(IDModel) , ZipCode , State FROM FACT_TRANSACTIONS F INNER JOIN DIM_LOCATION L ON F.IDLocation = L.IDLocation 
GROUP BY IDModel , ZipCode ,State
ORDER BY COUNT(IDMODEL) DESC

--4 SHOW THE CHEAPEST CELL PHONE

SELECT TOP 1 MODEL_NAME,MIN(UNIT_PRICE) PRICE FROM DIM_MODEL
GROUP BY Model_Name
ORDER BY MIN(UNIT_PRICE)

--5 FIND OUT THE AVERAGE PRICE FOR EACH MODEL IN TOP 5 MANUFACTURERS IN TERMS OF SALES QTY AND ORDER BY AVERAGE PRICE.

SELECT TOP 5
Manufacturer_Name,
AVG(TOTALPRICE) AVG_RATE,
SUM(QUANTITY)   SALE_QUANTITY
FROM FACT_TRANSACTIONS T1 
                          LEFT JOIN DIM_MODEL M1
                          ON T1.IDModel=M1.IDModel
                          INNER JOIN DIM_MANUFACTURER M2
                          ON M1.IDManufacturer=M2.IDManufacturer
GROUP BY Manufacturer_Name
ORDER BY SALE_QUANTITY DESC

--6 LIST THE NAMES OF CUSTOMER AND THE AVERAGE AMOUNT SPENT IN 2009 WHERE THE THE AVERAGE IS HIGHERR THAN 500.

SELECT CUSTOMER_NAME , AVG(F.TotalPrice) [AVERAGE PRICE]FROM DIM_CUSTOMER C INNER JOIN FACT_TRANSACTIONS F ON C.IDCustomer = F.IDCustomer
WHERE YEAR(F.Date) IN ('2009')
GROUP BY Customer_Name
HAVING AVG(F.TotalPrice) > 500
ORDER BY  AVG(F.TotalPrice) DESC

--7 LIST IF THERE IS ANY MODEL THAT WAS IN TOP 5  IN TEMS OF QUANTITY  SIMULTANEOUSLY IN 2008 , 2009 AND 2010

SELECT TOP 5
Model_Name,
SUM(QUANTITY)   SALE_QUANTITY
FROM FACT_TRANSACTIONS T1 LEFT JOIN DIM_MODEL M1 ON T1.IDModel=M1.IDModel
WHERE YEAR(T1.Date) IN ('2008','2009','2010')
GROUP BY Model_Name
ORDER BY SALE_QUANTITY DESC

--8 SHOW THE MANUFACTURER WITH THE 2ND TOP SALE IN THE YEAR 2009 AND MANUFACTURER IN WITH 2ND TOP SALES IN 2010

SELECT  top 1 * 
 from
    (SELECT 
    TOP 2 Manufacturer_name,
    SUM(Quantity )  TQ1
    FROM Fact_Transactions T1
    LEFT JOIN DIM_Model D1 ON T1.IDModel = D1.IDModel
    LEFT JOIN DIM_MANUFACTURER D2  ON D2.IDManufacturer = D1.IDManufacturer
    Where DATEPART(Year,date)='2009' 
    group by Manufacturer_name, Quantity 
    Order by  SUM(Quantity ) DESC ) as A,
	(SELECT 
    Top 2 Manufacturer_name,
     SUM(Quantity ) TQ2
    FROM Fact_Transactions T2
    LEFT JOIN DIM_Model DM ON T2.IDModel = DM.IDModel
    LEFT JOIN DIM_MANUFACTURER DM2  ON DM2.IDManufacturer = DM.IDManufacturer
    Where DATEPART(Year,date)='2010' 
    group by Manufacturer_name,Quantity
    Order by  SUM(Quantity )DESC ) as B

--9 Show the manufacturer that sold cellphone in 2009 but didn't in 2010

SELECT DISTINCT(MANUFACTURER_NAME) FROM FACT_TRANSACTIONS F INNER JOIN DIM_MODEL M ON F.IDModel = M.IDModel INNER JOIN DIM_MANUFACTURER M1 ON M.IDManufacturer = M1.IDManufacturer
WHERE YEAR(F.Date) IN ('2009') AND YEAR(F.DATE) NOT IN ('2010')

--10 Find top 100 customers and their average spend average quantity by each year. ALSO FIND THE PERCENTAGE OF CHANGE IN THEIR SPEND

SELECT TOP 100 
    YEAR(FT.DATE) AS [YEAR],
    FT.IDCUSTOMER AS [CUSTOMER NAME],
    FT.TotalPrice AS [TOTAL AMT],
    AVG(FT.TOTALPRICE) AS [AVG SPEND],
    AVG(FT.QUANTITY) AS [AVG QUANTITY]
INTO #DataSource
FROM 
    FACT_TRANSACTIONS FT
INNER JOIN 
    DIM_CUSTOMER DC ON FT.IDCUSTOMER = DC.IDCUSTOMER
GROUP BY 
    YEAR(FT.DATE), FT.IDCustomer, FT.TOTALPRICE
ORDER BY 
    [AVG SPEND] DESC 

SELECT *
      ,[AVG SPEND] - LAG([AVG SPEND], 1, 0) OVER (PARTITION BY [CUSTOMER NAME] ORDER BY [YEAR])
FROM #DataSource



